### ISSUE TITLE
Needs installation and usage instructions in README

### ISSUE THREAD

**Issue by jeffslofish** [alexcpendleton/sleep-tight#11]
I am trying to test this out for you on a couple different operating systems, but I can't figure out how to even run it, since there are no instructions. Looks interesting though!

**Comment by alexcpendleton** [comment]
Thanks for reaching out! I was honestly not expecting anyone to look at the help-wanted issues, let alone so quickly. I'll get on some instructions soon. The short version is to run 
`npm run hot` in one terminal and `npm run dev` in another.

**Comment by alexcpendleton** [comment]
Thanks for the PR too!

**Comment by jeffslofish** [comment]
No problem...I found you on http://issuehub.io
